version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt/certbot/conf:/etc/letsencrypt
      - ./letsencrypt/certbot/www:/var/www/certbot
    # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - richdiary-api

  certbot:
    image: "certbot/certbot"
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - ./letsencrypt/certbot/conf:/etc/letsencrypt
      - ./letsencrypt/certbot/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  richdiary-api:
    build: ./
    image: richdiary-api:1.0.0
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres-data:
  redis_data: